//
//  Typography+Span.swift
//  Span — type scale from DESIGN_SYSTEM.md.
//
//  Inter is the web stand-in; on iOS we use SF Pro (the system font) and let
//  Dynamic Type scale everything. Sizes mirror the iOS type ramp the comps were
//  built against (Apple HIG point sizes), exposed as named Span styles so screens
//  never hardcode point sizes.
//

import SwiftUI

enum SpanFont {
    /// Hero lab values / scores — 34 / bold.
    static let displayLarge = Font.system(size: 34, weight: .bold, design: .default)
    /// Alias used at data-value call-sites (same ramp as displayLarge).
    static let dataValueLg = Font.system(size: 34, weight: .bold, design: .default)
    /// Screen headers — 22 / semibold.
    static let title2 = Font.system(.title2, design: .default).weight(.semibold)
    /// Card titles / section groups — 17 / semibold.
    static let headline = Font.system(.headline, design: .default)
    /// Body copy — 17 / regular.
    static let body = Font.system(.body, design: .default)
    /// Secondary body — 16 / regular.
    static let callout = Font.system(.callout, design: .default)
    /// Persistent disclaimer + hints — 13 / regular.
    static let footnote = Font.system(.footnote, design: .default)
    /// Citation chips / source labels — 11 / medium.
    static let caption2 = Font.system(.caption2, design: .default).weight(.medium)
}

extension Font {
    /// Convenience accessor so call-sites read `Font.span.headline`.
    static let span = SpanFont.self
}

// MARK: - Reusable text styling modifiers

extension View {
    /// The persistent footer copy. Appended in code on every content screen —
    /// never generated by any AI model (SCREENS.md §"Persistent Footer").
    func spanDisclaimerStyle() -> some View {
        self.font(SpanFont.footnote)
            .foregroundStyle(SpanColor.textSecondary)
            .multilineTextAlignment(.center)
            .frame(maxWidth: .infinity)
    }

    /// Uppercase section header (".SYSTEM OVERVIEW", "READINGS", etc.).
    func spanSectionHeaderStyle() -> some View {
        self.font(SpanFont.footnote.weight(.semibold))
            .foregroundStyle(SpanColor.textSecondary)
            .textCase(.uppercase)
            .kerning(0.5)
    }
}
